// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDye1Yhkf_8ivbf0dmApiNhKcg9YmhIjg0',
    appId: '1:981875455201:web:f137a1615e6fd64cdc73a0',
    messagingSenderId: '981875455201',
    projectId: 'hw04-9421a',
    authDomain: 'hw04-9421a.firebaseapp.com',
    storageBucket: 'hw04-9421a.firebasestorage.app',
    measurementId: 'G-GK6007CKSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuw6QlZYr8FP06AMFsxTyieTGpl0gq7Y',
    appId: '1:981875455201:android:1bff14f965343e48dc73a0',
    messagingSenderId: '981875455201',
    projectId: 'hw04-9421a',
    storageBucket: 'hw04-9421a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpeZDCzHSaCcnN9VIL3DtLcwVaIAl7JzQ',
    appId: '1:981875455201:ios:0f0e3eea644bd3a3dc73a0',
    messagingSenderId: '981875455201',
    projectId: 'hw04-9421a',
    storageBucket: 'hw04-9421a.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpeZDCzHSaCcnN9VIL3DtLcwVaIAl7JzQ',
    appId: '1:981875455201:ios:0f0e3eea644bd3a3dc73a0',
    messagingSenderId: '981875455201',
    projectId: 'hw04-9421a',
    storageBucket: 'hw04-9421a.firebasestorage.app',
    iosBundleId: 'com.example.hw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDye1Yhkf_8ivbf0dmApiNhKcg9YmhIjg0',
    appId: '1:981875455201:web:34ca4609fb0bd0ffdc73a0',
    messagingSenderId: '981875455201',
    projectId: 'hw04-9421a',
    authDomain: 'hw04-9421a.firebaseapp.com',
    storageBucket: 'hw04-9421a.firebasestorage.app',
    measurementId: 'G-4MXMQR7HNP',
  );
}
